
--DROP TABLE transactions;
--DROP TABLE cards;
--DROP TABLE users;
--DROP TABLE dpan;
--DROP TABLE transactions_pre;

CREATE TABLE users (user_id integer GENERATED BY DEFAULT AS IDENTITY (start with 0 minvalue 0) NOT NULL PRIMARY KEY,
			  Person varchar (50),
			  Current_Age number,
			  Retirement_Age number,
			  Birth_Year number,
			  Birth_Month number,
			  Gender varchar (50),
			  Address varchar (50),
			  Apartment number,
			  City varchar (50),
			  State varchar (50),
			  Zipcode number,
			  Latitude number,
			  Longitude NUMBER,
			  Income varchar (50),
			  Yearly_Income varchar (50),
			  Total_Debt varchar (50),
			  FICO_Score number,
			  Cnt_Cards NUMBER);
			 
			 
CREATE TABLE cards (USER_ID NUMBER,
					CARD_INDEX NUMBER,
					Card_Brand varchar(15),
					Card_Type varchar(20),
					Card_Number varchar(50) UNIQUE,
					EXPIRES varchar (10),
					CVV number,
					Has_Chip varchar (3),
					Cards_Issued number,
					Credit_Limit varchar(20),
					Acct_Open_Date char(7),
					Year_PIN_last_Changed number,
				    CONSTRAINT prime_card PRIMARY KEY (USER_ID, CARD_INDEX),
				    CONSTRAINT fk_cards FOREIGN KEY (USER_ID) REFERENCES users (user_id));
					
			
CREATE TABLE transactions  (TRANSACTION_TIME DATE,
							User_id number,
							CARD number,
							AMOUNT number,
							Use_Chip varchar(20),
							Merchant_Name number,
							Merchant_City varchar(30),
							Merchant_State varchar(20),
							ZIP number,
							MCC number,
							ERR varchar(50),
							create_dt DATE,
							update_dt DATE,
						    CONSTRAINT prime_trans PRIMARY KEY (TRANSACTION_TIME, User_id, CARD),
						    CONSTRAINT fk_trans_card FOREIGN KEY (card, user_id) REFERENCES cards (card_index, user_id));
						
						   

CREATE TABLE transactions_pre  (n integer GENERATED BY DEFAULT AS IDENTITY (start with 1 minvalue 1) NOT NULL,
							TRANSACTION_TIME varchar(50),
							User_id number,
							CARD number,
							AMOUNT number,
							Use_Chip varchar(20),
							Merchant_Name number,
							Merchant_City varchar(30),
							Merchant_State varchar(20),
							ZIP number,
							MCC number,
							ERR varchar(50));
						   
CREATE TABLE DPAN (mas varchar(20),
				   num NUMBER );
